version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
